#include <map>
using namespace std;

class Optable{
public:
    Optable(string opcode, int format) : opcode(opcode), format(format) {}
    string opcode;
    int format;
};

const map<string, Optable> OPTABLE = {
    {"ADD", Optable("18", 3)},
    {"ADDF", Optable("58", 3)},
    {"ADDR", Optable("90", 2)},
    {"AND", Optable("40", 3)},
    {"CLEAR", Optable("B4", 2)},
    {"COMP", Optable("28", 3)},
    {"COMPF", Optable("88", 3)},
    {"COMPR", Optable("A0", 2)},
    {"DIV", Optable("24", 3)},
    {"DIVF", Optable("64", 3)},
    {"DIVR", Optable("9C", 2)},
    {"FIX", Optable("C4", 1)},
    {"FLOAT", Optable("C0", 1)},
    {"HIO", Optable("F4", 1)},
    {"J", Optable("3C", 3)},
    {"JEQ", Optable("30", 3)},
    {"JGT", Optable("34", 3)},
    {"JLT", Optable("38", 3)},
    {"JSUB", Optable("48", 3)},
    {"LDA", Optable("00", 3)},
    {"LDB", Optable("68", 3)},
    {"LDCH", Optable("50", 3)},
    {"LDF", Optable("70", 3)},
    {"LDL", Optable("08", 3)},
    {"LDS", Optable("6C", 3)},
    {"LDT", Optable("74", 3)},
    {"LDX", Optable("04", 3)},
    {"LPS", Optable("D0", 3)},
    {"MUL", Optable("20", 3)},
    {"MUL", Optable("20", 3)},
    {"MULF", Optable("60", 3)},
    {"MULR", Optable("98", 2)},
    {"NORM", Optable("C8", 1)},
    {"OR", Optable("44", 3)},
    {"RD", Optable("D8", 3)},
    {"RMO", Optable("AC", 2)},
    {"RSUB", Optable("4C", 3)},
    {"SHIFTL", Optable("A4", 2)},
    {"SHIFTR", Optable("A8", 2)},
    {"SIO", Optable("F0", 1)},
    {"SSK", Optable("EC", 3)},
    {"STA", Optable("0C", 3)},
    {"STB", Optable("78", 3)},
    {"STCH", Optable("54", 3)},
    {"STF", Optable("80", 3)},
    {"STI", Optable("D4", 3)},
    {"STL", Optable("14", 3)},
    {"STS", Optable("7C", 3)},
    {"STSW", Optable("E8", 3)},
    {"STT", Optable("84", 3)},
    {"STX", Optable("10", 3)},
    {"SUB", Optable("1C", 3)},
    {"SUBF", Optable("5C", 3)},
    {"SUBR", Optable("94", 2)},
    {"SVC", Optable("B0", 2)},
    {"TD", Optable("E0", 3)},
    {"TIO", Optable("F8", 1)},
    {"TIX", Optable("2C", 3)},
    {"TIXR", Optable("B8", 2)},
    {"WD", Optable("DC", 3)},
};
